services:
  frontend:
    build: 
      context: ./queuesmart
      target: dev
    image: queuesmart-frontend:dev
    container_name: queuesmart-frontend-dev
    develop:
      watch:
        - action: rebuild
          path: ./queuesmart/package.json
        - action: rebuild
          path: ./queuesmart/package-lock.json
        - action: rebuild
          path: ./queuesmart/Dockerfile
        - action: rebuild
          path: ./queuesmart/vite.config.ts

        - action: sync
          path: ./queuesmart
          target: /app
          ignore:
            - node_modules
            - .git
            - dist
    ports:
      - "5173:5173"
  backend:
    build:
      context: ./backend
      target: dev
    image: queuesmart-backend:dev
    container_name: queuesmart-backend-dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /source
          ignore:
            - bin/
            - obj/
            - .git/
            - backend.csproj
            - Dockerfile
            
        - action: rebuild
          path: ./backend/backend.csproj
        - action: rebuild
          path: ./backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
  db:
    image: postgres:17-alpine
    container_name: queuesmart-db-dev
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: