@backend_HostAddress = https://localhost:7294

# Uncomment if running docker dev container
@backend_HostAddress = http://localhost:8080

GET {{backend_HostAddress}}/
Accept: application/json

###
GET {{backend_HostAddress}}/service
Accept: application/json

###
POST {{backend_HostAddress}}/service
Accept: application/json
Content-Type: application/json

{
    "Name": "First Service",
    "Description": "This is my very first service created",
    "Priority": "Low",
    "Duration": 20
}

###
GET {{backend_HostAddress}}/service/1
Accept: application/json

###
PUT {{backend_HostAddress}}/service/1
Accept: application/json
Content-Type: application/json

{
    "Name": "UPDATED: First Service",
    "Description": "This is the first service that was updated",
    "Duration": 30,
    "Priority": "High"
}

###
GET {{backend_HostAddress}}/queue
Accept: application/json

###
POST {{backend_HostAddress}}/queue
Accept: application/json
Content-Type: application/json

# DateOnly must be in yyyy-MM-dd format
{
  "Status": "Open",
  "ServiceId": 1
}